# name of the action
name: build

# trigger on pull_request or push events
on:
  pull_request:
  push:

# pipeline to execute
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: clone
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

    - name: install go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
      with:
        # use version from go.mod file
        go-version-file: 'go.mod'
        cache: true
        check-latest: true

    - name: build
      run: |
        make build
